### ISSUE TITLE
How do we approach nested resources in Apiato?

### ISSUE THREAD

**Issue by R00118189** [llstarscreamll/Crud#3]
I generated post comment and reply containers but am stuck on nested resources, shall the highest lever resource have multiple controllers which use actions from other containers like 
`PostCommentController` in Post container alongside with `PostController` and `CommentReplyController` in Reply container OR `PostCommentReplyController` in Post container

**Comment by llstarscreamll** [comment]
hi, you should do this the way your business tells you, for example, if currently you only need to get post comments, implement that feature by putting your logic on the **posts** controller/action/task ... whatever ... `posts/{post_id}/comments`. Why? you should work on functionalities that are really needed, don't waste time on things that maybe you will never use, if things are growing up, then you should move all the things around and implement whatever you are needing:

`posts/{post_id}/comments/{comment_id}`
`posts/{post_id}/comments/{comment_id}/reply/{reply_id}`
`comments/{comment_id}/reply/{reply_id}`
`comments/{comment_id}/reply/{reply_id}`

The resource names will give you a clear idea how to organize your code.
If you have a subscription on laracast, here are some good explanations:

[How Do I Create Nested Comments](https://laracasts.com/series/how-do-i/episodes/9)
[Tags and Nested Resources](https://laracasts.com/series/incremental-api-development/episodes/9)

Maybe this can help too:

http://jsonapi.org/format/

Cheers!!
